name: Build Arch Linux KDE ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO inside Arch Linux Docker Container
        uses: jonasfraether/archiso-action@v1
        with:
          recipe: profile

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-kde-iso
          path: out/*.iso
