# Force update build configuration 2026
name: Build ISO
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Update Keys
        run: pacman -Sy --noconfirm archlinux-keyring git
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ISO
        uses: coderadu/actions-mkarchiso@v1
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-iso
          path: out/.
